[package]
name = "synedao"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.1.0" }
cosmwasm-schema = { version = "1.1.0" }
cw-storage-plus = "1.0.1"
cw-utils = "1.0.1"
cw2 = { version = "1.0.1" }
cw20 = { version = "1.0.1" }
cw3 = { version = "1.0.1" }
cw4 = { version = "1.0.1" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.23"
syne-curve-utils = { path = "../syne-curve-utils", default-features = false }

[dev-dependencies]
anyhow = "1"
cosmwasm-schema = "1.1.0"
